# name: Build-Snap-Edge

# on:
#   pull_request:
#     branches: [ master ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         token: ${{ secrets.PAT }}
#     - uses: snapcore/action-build@v1
#       id: snapcraft
#     - uses: snapcore/action-publish@v1
#       with:
#         store_login: ${{ secrets.STORE_LOGIN }}
#         snap: ${{ steps.snapcraft.outputs.snap }}
#         release: beta
